Instructors/urls.py
app_name='Instructors'
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.view_instructos,name='view_instructos'),
     path('<str:slug>',views.view_instructor,name='view_instructor'),
]

about/urls.py
app_name="about"
from django.urls import path 
from . import views
urlpatterns = [
path('',views.render_about,name="about_render" ),
]

home/urls.py
app_name='home'
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.home_render,name='home_render'),
]

online_course/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('accounts/', include('accounts.urls',namespace='accounts_detials')),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('instructor/',include('Instructors.urls',namespace='instructors')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('courses/', include('course.urls',namespace='courses')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

home/views.py
from multiprocessing import context
from django.shortcuts import render
from Instructors.models import Instructor
def home_render(request):
    instructor_list=Instructor.objects.all()
    context={"instructor_list":instructor_list}
    return render(request,'index.html',context)

home/templates/index.html
{% extends 'base.html' %}
{%load static %}

<title> {% block title %} Home
    {% endblock %}</title>
    <h1 class="display-3 text-white animated slideInDown">
        {% block  pagename %}
        Home
        {% endblock pagename  %}
            </h1>
{%block body%}
    <!-- Service Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-4">
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="service-item text-center pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-graduation-cap text-primary mb-4"></i>
                            <h5 class="mb-3">Skilled Instructors</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="service-item text-center pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-globe text-primary mb-4"></i>
                            <h5 class="mb-3">Online Classes</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="service-item text-center pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-home text-primary mb-4"></i>
                            <h5 class="mb-3">Home Projects</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <div class="service-item text-center pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-book-open text-primary mb-4"></i>
                            <h5 class="mb-3">Book Library</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->
    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <img class="img-fluid position-absolute w-100 h-100" src="{%static 'img/about.jpg' %}" alt="" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.3s">
                    <h6 class="section-title bg-white text-start text-primary pe-3">About Us</h6>
                    <h1 class="mb-4">Welcome to eLEARNING</h1>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.</p>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                    <div class="row gy-2 gx-4 mb-4">
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Skilled Instructors</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Online Classes</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>International Certificate</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Skilled Instructors</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Online Classes</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>International Certificate</p>
                        </div>
                    </div>
                    <a class="btn btn-primary py-3 px-5 mt-2" href="{% url 'about:about_render' %}">Read More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
  <!-- Categories Start -->
  <!-- Categories End -->
  <!-- Courses Start -->
 <!-- Courses end -->

     <!-- Team Start -->
     <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Instructors</h6>
                <h1 class="mb-5">Expert Instructors</h1>
            </div>
            <div class="row g-4">
                {%for i in instructor_list%}  
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <a href="{% url 'instructors:view_instructor' i.slug%}"><img class="img-fluid" src="{{i.image.url}}" alt=""></a>
                        </div>
                        <div class="position-relative d-flex justify-content-center" style="margin-top: -23px;">
                            <div class="bg-light d-flex justify-content-center pt-2 px-1">
                                <a class="btn btn-sm-square btn-primary mx-1" href="{{i.github}}"><i class="fab fa-github"></i></a>
                                <a class="btn btn-sm-square btn-primary mx-1" href="{{i.linkdin}}"><i class="fab fa-linkedin"></i></a>
                                <a class="btn btn-sm-square btn-primary mx-1" href="{{i.facebook}}"><i class="fab fa-facebook "></i></a>
                            </div>
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">{{i.name}}</h5>
                            <small>{{i.job}}</small>
                        </div>
                    </div>
                </div>
                
             {% endfor %}    
             <a class="btn btn-primary py-3 px-5 mt-2" href="{% url 'instructors:view_instructos' %}">See More</a>
            </div>
        </div>
    </div>
    <!-- Team End -->

      <!-- Testimonial Start -->
      <!-- Testimonial end -->




      {%endblock body%}