Instructors/urls.py
app_name='Instructors'
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.view_instructos,name='view_instructos'),
     path('<str:slug>',views.view_instructor,name='view_instructor'),
]

course/urls.py
app_name="course"
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.course_render,name='view_course'),
     path('<str:slug>',views.single_course,name='view_single_course'),
]

home/urls.py
app_name='home'
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.home_render,name='home_render'),
]

online_course/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('accounts/', include('accounts.urls',namespace='accounts_detials')),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('instructor/',include('Instructors.urls',namespace='instructors')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('courses/', include('course.urls',namespace='courses')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from Instructors.models import Instructor
from django.contrib.auth.models import User
from django.utils.text import slugify
class courses(models.Model):
    instructor_name=models.ForeignKey(Instructor,related_name="Course_instructor",on_delete=models.CASCADE)
    course_name=models.CharField(max_length=150)
    course_price=models.IntegerField(default=0)
    course_houre=models.IntegerField(default=0)
    course_Student=models.IntegerField(default=0)
    slug = models.SlugField(null=True,blank=True)  
    course_image=models.ImageField(upload_to="course_image",default="image.png" )
    course_rate=models.DecimalField(max_digits=5, decimal_places=1,default=0.0)
    def __str__(self):
        return self.course_name
    def save(self,*args,**kwargs):
        self.slug=slugify(self.course_name)
        super(courses,self).save(*args,**kwargs)
class comments(models.Model):
    courses=models.ForeignKey(courses,related_name="comment_course",on_delete=models.CASCADE)
    comment_owner=models.ForeignKey(User,related_name='comment_owner',on_delete=models.CASCADE)
    data=models.DateTimeField(auto_now_add=True)
    comment=models.TextField(max_length=1500)

    

course/forms.py
from django import forms
from .models import comments

class commentForm(forms.ModelForm):
    class Meta:
        model = comments
        fields = ['comment',]

course/views.py
from multiprocessing import context
from django.shortcuts import render
from .models import courses,comments

def course_render(request):
    courses_list=courses.objects.all()
    return render(request,'Course_list.html',{'courses_list':courses_list})
def single_course(request,slug):
    course=courses.objects.get(slug=slug)
    context={'course':course}
    return render(request,'Single_Course.html',context)

course/templates/Course_list.html
{% extends 'base.html' %}
{%load static %}
<title> {% block title %} Courses
    {% endblock %}</title>
    <h1 class="display-3 text-white animated slideInDown">
        {% block  pagename %}
        Courses
        {% endblock pagename  %}
            </h1>
{%block body%}




    <!-- Courses Start -->
    <div class="container-xxl py-5">
      <div class="container">
          <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
              <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>
              <h1 class="mb-5">Popular Courses</h1>
          </div>
          
          <div class="row g-4 justify-content-center">
            {%for c in courses_list%}
              <div class="col-lg-4 col-md-6 course" data-wow-delay="0.1s">
                  <div class="course-item bg-light">
                      <div class="position-relative overflow-hidden">
                          <img class="img-fluid " src="{{c.course_image.url}}" alt="" width="397px">
                          <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                              <a href="{%url 'courses:view_single_course' c.slug%}" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                              <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                          </div>
                      </div>
                      <div class="text-center p-4 pb-0">
                          <h3 class="mb-0">${{c.course_price}}</h3>
                          <div class="mb-3">
                              <small>({{c.course_rate}})</small>
                          </div>
                          <h5 class="mb-4">{{c.course_name}}</h5>
                      </div>
                      <div class="d-flex border-top">
                          <small class="flex-fill text-center border-end py-2"><a href="{% url 'instructors:view_instructor' c.instructor_name.slug%}"><i class="fa fa-user-tie text-primary me-2"></i>{{c.instructor_name}}</a></small>
                          <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>{{c.course_houre}} Hrs</small>
                          <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>{{c.course_Student}} Students</small>
                      </div>
                  </div>
              </div>
            {%endfor%}
          </div>
      </div>
  </div>
  <!-- Courses End -->



{%endblock body%}

course/templates/Single_Course.html
{% extends 'base.html' %}
{%load static %}
<title> {% block title %} {{course.course_name}}
    {% endblock %}</title>
    <h1 class="display-3 text-white animated slideInDown">
        {% block  pagename %}
        {{course.course_name}}
        {% endblock pagename  %}
        </h1>
{%block body%}
<div class="container">
    <div class="row ">
        <div class="col-12 d-flex justify-content-center">
            <img class="image-fluid  w-50" src="{{course.course_image.url}}">
        </div>
    </div>   
</div>
<hr>
<div class="container p-12">
    <div class="row ">
        <div class="col-12 d-flex justify-content-center">
            <h3>Content<h3>
        </div>
    </div>   
</div>

{%endblock body%}