accounts/urls.py
from django.urls import include, path
from . import views
app_name='accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
  
    path('profile/edit',views.profile_edit,name='profile_edit'),
    
]

home/urls.py
app_name='home'
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.home_render,name='home_render'),
]

online_course/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('accounts/', include('accounts.urls',namespace='accounts_detials')),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('instructor/',include('Instructors.urls',namespace='instructors')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('courses/', include('course.urls',namespace='courses')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from distutils.command.upload import upload
from email.mime import image
from email.policy import default
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.dispatch import receiver

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="profile/" ,default='default.jpg')
    slug = models.SlugField(null=True,blank=True)  
    def __str__(self):
        return self.user.username
    def save(self,*args,**kwargs):
        self.slug=slugify(self.user.username)
        super(Profile,self).save(*args,**kwargs)
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


    

accounts/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password1','password2',]

class EditUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','email','username']
class EditProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['image']
        

accounts/views.py
from django.urls import reverse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from .forms import SignupForm,EditProfileForm,EditUserForm
from .models import Profile
# Create your views here.
def signup(request):
    if request.method=="POST":
        form=SignupForm(request.POST)
        if form.is_valid:
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/')
        else:
            return render(request,'registration/signup.html',{'form':form})
    else:
        form=SignupForm()
    return render(request,'registration/signup.html',{'form':form})


def viewprofile(request,slug):
    profile=Profile.objects.get(slug=slug)
    return render(request,'accounts/profile.html',{'profile':profile})
def profile(request):
    profile=Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})
def profile_edit(request):
    profile=Profile.objects.get(user=request.user)
    if request.method=='POST':
         userform=EditUserForm(request.POST,request.FILES,instance=request.user)
         profileform=EditProfileForm(request.POST,request.FILES,instance=profile)
         if userform.is_valid and profileform :
            myprofile=profileform.save(commit=False)
            myprofile.user=request.user
            myprofile.save()
            userform.save()
            return redirect(reverse('accounts:profile'))
            
    else:
         userform=EditUserForm(instance=request.user)
         profileform=EditProfileForm(instance=profile)
    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform})
    
def logout_view(request):
    logout(request)
    

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{%load static %}

<title> {% block title %} {{profile.user.username}}
    {% endblock %}</title>
    <h1 class="display-3 text-white animated slideInDown">
        {% block  pagename %}
        {{profile.user.first_name}} {{profile.user.last_name}} 
        {% endblock pagename  %}
            </h1>
{% block body %}


    <div class="job_details_area">
        <div class="container">
            <div class="row">

                <div class="col-lg-10 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            
                            
                            {% if profile.image %}
                                <img class="w-50 mb-10 mx-auto rounded d-block img-thumbnail " src="{{profile.image.url}}" alt="">
                                {% else %}
                                <img class="w-50 mb-10 mx-auto rounded d-block img-thumbnail " src="omg.png" alt="">
                            {% endif %}
                                
                           
                         <span class="d-block text-center text-capitalize font-weight-bold">{{profile.user.first_name}} {{profile.user.last_name}}</span>
                        
                            
                        </div>
                        <div class="job_content">
                            <ul>           
                                <li>Username: <span>{{profile.user.username}} </span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Joined Date: <span>{{profile.user.date_joined}}</span></li>
                                <li> Number Of Courses: </li>
                            </ul>
                            
                        </div>
                        <div class="p-3">
                            <a href="{% url 'accounts:profile_edit' %}"><button class="btn btn-success boxed-btn3 w-100">Edit Profile</button></a>
                         </div>
                         <hr>
                         <div class="p-3">
                            <h4 class="text-center">My Courses<h4>
                         </p>
                        
                    </div>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}

   

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{%load static %}

<title> {% block title %} Personal Information
    {% endblock %}</title>
    <h1 class="display-3 text-white animated slideInDown">
        {% block  pagename %}
        Personal Information
        {% endblock pagename  %}
            </h1>
{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
 
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class=" mx-auto ">
                <div class="apply_job_form white-bg">
                    <h3>Edit Profile</h3>
                        {% load bootstrap4 %}                
                        <form method="post" class="form" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% bootstrap_form userform %}
                         {% bootstrap_form profileform %}
                         {% buttons %}
                        <button type="submit" class="btn btn-primary btn-lg mt-2">Change</button>
                        {% endbuttons %}
                      </form>
                </div>
                </div>
        </div>
    </div>
    {% endblock body %}

   