about/urls.py
app_name="about"
from django.urls import path 
from . import views
urlpatterns = [
path('',views.render_about,name="about_render" ),
]

accounts/urls.py
from django.urls import include, path
from . import views
app_name='accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
  
    path('profile/edit',views.profile_edit,name='profile_edit'),
    
]

contact/urls.py
from django.urls import include, path
from . import views
app_name='contact'
urlpatterns = [
    path('',views.send_message,name='contact'),
    path('success',views.sucessful,name='success'),
    
]

course/urls.py
app_name="course"
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.course_render,name='view_course'),
     path('<str:slug>',views.single_course,name='view_single_course'),
]

home/urls.py
app_name='home'
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.home_render,name='home_render'),
]

online_course/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('accounts/', include('accounts.urls',namespace='accounts_detials')),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('instructor/',include('Instructors.urls',namespace='instructors')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('courses/', include('course.urls',namespace='courses')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static  %} 
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title> {% block title %}
            {% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    {% fontawesome_5_static %}
    <!-- Favicon -->
    <link href="{% static 'css/css2.css' %}" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

    <!-- Navbar Start -->
   <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{%url 'home:home_render' %}" class="nav-item nav-link">Home</a>
            <a href="{% url 'about:about_render' %}" class="nav-item nav-link">About</a>
            <a href="{% url 'courses:view_course' %}" class="nav-item nav-link">Courses</a>
            <a href="{% url 'instructors:view_instructos' %}" class="nav-item nav-link ">Our Team</a>
            <a href="{% url 'contact:contact' %}" class="nav-item nav-link">Contact</a>
            {%if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle " data-bs-toggle="dropdown">Profile</a>
                <div class="dropdown-menu m-0">
                    <a href="{%url 'accounts_detials:profile' %}" class="dropdown-item ">{{user.first_name}} {{user.last_name}} </a>
                    <a href="{%url 'accounts_detials:profile_edit' %}" class="dropdown-item ">Edit Personal Information </a>
                    <a href="{%url 'password_change' %}" class="dropdown-item ">Change Password </a>
                </div>
            </div>
            <a href="{%url 'logout' %} " class="nav-item   btn btn-primary py-4 px-lg-5  d-lg-block">log out<i class="fa fa-arrow-right ms-3"></i></a>
            {%else %}
            <a href="{%url 'login' %} " class="nav-item  btn btn-primary py-4 px-lg-5  d-lg-block">log in<i class="fa fa-arrow-right ms-3"></i></a>
            {%endif%}
            
        </div>
      
        
    </div>
</nav>
<!-- Navbar End -->

  <!-- Navbar End -->

    <!-- Header Start -->

    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">
                    {% block  pagename %}
                        
                    {% endblock pagename  %}
                        </h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
  <!-- Header End -->

{%block body%}
{%endblock body%}
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
      <div class="container py-5">
          <div class="row g-5">
              <div class="col-lg-6 col-md-6">
                  <h4 class="text-white mb-3">Quick Link</h4>
                  <a class="btn btn-link" href="">About Us</a>
                  <a class="btn btn-link" href="">Contact Us</a>
                  <a class="btn btn-link" href="">Privacy Policy</a>
                  <a class="btn btn-link" href="">Terms & Condition</a>
                  <a class="btn btn-link" href="">FAQs & Help</a>
              </div>
              <div class="col-lg-6 col-md-6">
                  <h4 class="text-white mb-3">Contact</h4>
                  <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                  <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                  <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                  <div class="d-flex pt-2">
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                  </div>
              </div>
      </div>
   
  </div>
  <!-- Footer End -->


  <!-- Back to Top -->
  <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fae fa fa-arrow-up ms-3"></i></a>

    <!-- Template Javascript -->
    <script src="{%static 'js/main.js' %}"></script>
    <!-- JavaScript Libraries -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>

templates/base_generic.html
{% extends 'base.html' %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
      
        </div>
    </div>
    <!--/ bradcam_area  -->
        <div class="container">
            <div class=" mx-auto ">

                    
                    {% block content %}
                        
                    {% endblock content %}
                        
                </div>
                </div>

         </div>
    {% endblock body %}

   